// // This file was generated by Prisma, and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });
import { defineConfig } from 'prisma/config';
import * as dotenv from 'dotenv';

dotenv.config();

export default defineConfig({
  schema: 'libs/backend/shared/database/prisma/schema.prisma',
  migrations: {
    path: 'libs/backend/shared/database/prisma/migrations',
    seed: 'ts-node --project tsconfig.base.json --transpile-only libs/backend/shared/database/prisma/seed.ts',
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
